--Ecommerce Project

--Basic Queries
--1. List all unique cities where customers are located.
SELECT * FROM customers;

SELECT DISTINCT(customer_city) AS unique_cities FROM customers;

--2. Count the number of orders placed in 2017.
SELECT * FROM orders LIMIT 5;

SELECT COUNT(order_id) AS no_of_orders
FROM orders 
WHERE EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) = 2017;



--3. Find the total sales per category.

SELECT * FROM products LIMIT 5;
SELECT * FROM order_items LIMIT 5;
SELECT * FROM payments LIMIT 5;

--Rename the column product category to product_category

ALTER TABLE products 
RENAME column "product category" TO "product_category";

SELECT pd.product_category, ROUND(SUM(pm.payment_value)::numeric,2) AS total_sales
FROM products AS pd
INNER JOIN order_items AS o
ON pd.product_id = o.product_id
INNER JOIN payments as pm
ON o.order_id = pm.order_id
GROUP BY 1;

--4. Calculate the percentage of orders that were paid in installments.
SELECT * FROM payments;

SELECT (100*(SUM(CASE WHEN payment_installments>=1 THEN 1 ELSE 0 END)::numeric)/COUNT(*)) AS percentage_of_orders
FROM payments;

--5. Count the number of customers from each state.


SELECT customer_state, COUNT(customer_id) AS no_of_customers
FROM customers
GROUP BY 1;



--INTERMEDIATE QUERIES

--1. Calculate the number of orders per month in 2018.
SELECT * FROM orders;

SELECT EXTRACT(MONTH FROM order_purchase_timestamp::timestamp) AS months_2018,COUNT(order_id) AS no_of_orders
FROM orders
WHERE EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) = 2018
GROUP BY 1;


SELECT TO_CHAR(order_purchase_timestamp::timestamp, 'Month') AS month_name,COUNT(order_id) AS no_of_orders
FROM orders
WHERE EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) = 2018
GROUP BY 1
ORDER BY MIN(order_purchase_timestamp::timestamp);

--2. Find the average number of products per order, grouped by customer city.

SELECT * FROM customers;
SELECT * FROM order_items;
SELECT * FROM orders;

WITH count_orders AS
	(
	SELECT o.order_id,o.customer_id,COUNT(oi.order_item_id) AS oc
	FROM orders as o
	INNER JOIN order_items as oi
	ON o.order_id = oi.order_id
	GROUP BY 1,2
	)

SELECT c.customer_city,ROUND(AVG(co.oc),2) AS avg_no_orders
FROM customers as c
INNER JOIN count_orders as co
ON c.customer_id = co.customer_id
GROUP BY 1;



--3. Calculate the percentage of total revenue contributed by each product category.
SELECT * FROM payments LIMIT 5;
SELECT * FROM products;
SELECT * FROM order_items;

WITH total_rev AS
(
	SELECT pd.product_category,ROUND(SUM(pm.payment_value::numeric),2) AS total_revenue
	FROM products AS pd
	INNER JOIN order_items as oi
	ON pd.product_id = oi.product_id
	INNER JOIN payments as pm
	ON oi.order_id = pm.order_id
	GROUP BY 1
)

SELECT product_category,ROUND(100*(total_revenue/(SELECT SUM(payment_value) FROM payments))::numeric,2) AS Percentage_of_total_revenue
FROM total_rev
ORDER BY 2 DESC;


--4. Identify the correlation between product price and the number of times a product has been purchased.

SELECT * FROM payments LIMIT 5;
SELECT * FROM products LIMIT 5;
SELECT * FROM order_items LIMIT 5;

SELECT pd.product_category,count(oi.product_id) AS no_times_product_purchased,ROUND(AVG(oi.price)::numeric,2) AS avg_price
FROM products as pd
INNER JOIN order_items as oi
ON pd.product_id = oi.product_id
GROUP BY 1;





--5. Calculate the total revenue generated by each seller, and rank them by revenue.

SELECT * FROM sellers;
SELECT * FROM order_items;
SELECT * FROM payments;

WITH total_rev AS 
(
	SELECT s.seller_id AS s_id,ROUND(SUM(pm.payment_value)::numeric,2) AS total_revenue
	FROM sellers as s
	INNER JOIN order_items as oi
	ON s.seller_id = oi.seller_id
	INNER JOIN payments as pm
	ON pm.order_id = oi.order_id
	GROUP BY 1
	ORDER BY 2 DESC
)

SELECT *, DENSE_RANK() OVER(ORDER BY total_revenue DESC)
FROM total_rev;


--ADVANCED QUERIES

--1. Calculate the moving average of order values for each customer over their order history.
SELECT * FROM payments LIMIT 5;
SELECT * FROM orders LIMIT 5;


WITH pm_table AS
(
SELECT o.customer_id,o.order_purchase_timestamp,pm.payment_value AS payment
FROM orders as o
JOIN payments as pm
ON o.order_id = pm.order_id
)

SELECT customer_id,order_purchase_timestamp,
	AVG(payment) OVER(PARTITION BY customer_id ORDER BY order_purchase_timestamp ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg
FROM pm_table;


--2. Calculate the cumulative sales per month for each year.
SELECT * FROM payments;
SELECT * FROM orders LIMIT 5;

WITH total_sales AS
(
	SELECT EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) AS year,
		TO_CHAR(order_purchase_timestamp::timestamp,'Month') AS month_name, 
		ROUND(SUM(payment_value)::numeric,2) AS sales
	FROM orders as o
	JOIN payments as pm
	ON o.order_id = pm.order_id
	GROUP BY 1,2
	ORDER BY MIN(order_purchase_timestamp::timestamp)
)

SELECT year,month_name,sales, SUM(sales) OVER(PARTITION BY year ORDER BY month_name) AS cummulative_sales
FROM total_sales;


--3. Calculate the year-over-year growth rate of total sales.

WITH yearly_sales AS 
(
	SELECT EXTRACT(YEAR FROM o.order_purchase_timestamp::timestamp) AS year,ROUND(SUM(pm.payment_value)::numeric,2) AS total_sales
	FROM orders as o
	JOIN payments as pm
	ON o.order_id = pm.order_id
	GROUP BY 1
	ORDER BY 1
)

SELECT year,total_sales,
	LAG(total_sales) OVER(ORDER BY year) AS previous_year_sales,
	ROUND(((total_sales - LAG(total_sales) OVER(ORDER BY year))/ LAG(total_sales) OVER(ORDER BY year)*100)::numeric,2) AS year_on_year_growth
FROM yearly_sales;



--4. Calculate the retention rate of customers, defined as the percentage of customers
--who make another purchase within 6 months of their first purchase.

--first lets find the first order of customers
WITH first_purchase AS
(
	SELECT customer_id,MIN(order_purchase_timestamp::timestamp) AS first_order_date
	FROM orders
	GROUP BY 1
),

retained_customers AS   ---find the retained customers after first purchase and interval of 6months
(
	SELECT o.customer_id
	FROM orders as o
	JOIN first_purchase as fp
		ON o.customer_id = fp.customer_id
	WHERE order_purchase_timestamp::timestamp > fp.first_order_date 
	AND order_purchase_timestamp::timestamp <= fp.first_order_date + INTERVAL '6 months'
)

SELECT COUNT(DISTINCT rc.customer_id) AS retained_customers, 
	COUNT(DISTINCT fp.customer_id) AS total_customers,
    ROUND(COUNT(DISTINCT rc.customer_id)::numeric/ COUNT(DISTINCT fp.customer_id) * 100,2) AS retention_rate_percentage
FROM first_purchase fp
LEFT JOIN retained_customers rc
    ON fp.customer_id = rc.customer_id;




--5. Identify the top 3 customers who spent the most money in each year.

WITH all_customers AS 
(
	SELECT customer_id,EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) AS year,SUM(payment_value) AS spent_money,
		DENSE_RANK() OVER(PARTITION BY EXTRACT(YEAR FROM order_purchase_timestamp::timestamp) ORDER BY SUM(payment_value) DESC) AS rank
	FROM orders as o
	JOIN payments as pm
	ON o.order_id = pm.order_id
	GROUP BY 1,2
)

SELECT customer_id,year,spent_money,rank
FROM all_customers
WHERE rank < 4;








